export const SOIL_MOISTURE_FETCH_REQUEST = "SOIL_MOISTURE_FETCH_REQUEST"
export const SOIL_MOISTURE_FETCH_SUCCESS = "SOIL_MOISTURE_FETCH_SUCCESS"
export const SOIL_MOISTURE_FETCH_FAILURE = "SOIL_MOISTURE_FETCH_FAILURE"